Ensf400 ws24 parsa
growlf/toolbox pull request #117
Opened 2024-02-15 18:26 UTC by ParsaKargari

2024-02-16 17:51 UTC, CDEguia commented on docker-compose.yml
> +    command: ["/bin/zsh"] # default command
This will override the default command specified in the docker file
```suggestion
    command: ["/bin/zsh"] # override default command
```

2024-02-16 17:54 UTC, CDEguia requested changes
True comments, one change requested. 
This is a good start, might as well continue for consistency to add comments to every line

2024-02-25 19:44 UTC, abarcomb-work commented
Pull requests should contain useful information about the reasoning behind the changes for the repository maintainer to enable them to prioritize PRs. This is part of the collaborative workflow.

2024-02-25 19:44 UTC, abarcomb-work commented
The PR should have been made to the ensf400-ws24 branch, not to main.

2024-02-25 20:17 UTC, closed without merging